// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Steam2Api.Data;

#nullable disable

namespace Steam2Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802080042_AddPaypal")]
    partial class AddPaypal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Steam2Api.Entities.GameEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("UpdateCreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_by_id");

                    b.Property<DateTime>("UpdateCreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_date");

                    b.HasKey("Id");

                    b.ToTable("juegos");
                });

            modelBuilder.Entity("Steam2Api.Entities.InvoiceDetailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.Property<string>("UpdateCreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_by_id");

                    b.Property<DateTime>("UpdateCreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_date");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("detalle_facturas");
                });

            modelBuilder.Entity("Steam2Api.Entities.InvoiceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<string>("UpdateCreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_by_id");

                    b.Property<DateTime>("UpdateCreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("Steam2Api.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("UpdateCreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_by_id");

                    b.Property<DateTime>("UpdateCreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_created_date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Steam2Api.Entities.InvoiceDetailEntity", b =>
                {
                    b.HasOne("Steam2Api.Entities.GameEntity", "Game")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steam2Api.Entities.InvoiceEntity", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Steam2Api.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("Steam2Api.Entities.UserEntity", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steam2Api.Entities.GameEntity", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Steam2Api.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Steam2Api.Entities.UserEntity", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
